### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by numeroteca** [skotperez/wpmap#13]
In the website http://globalrec.org/waw/waste-picker-organizations-map, and in all the other maps, the plugin stopped working @skotperez 
Any idea why?

**Comment by skotperez** [comment]
This issue should to be fixed in [WPMap version 0.4](https://github.com/skotperez/wpmap/releases/tag/v0.4). @numeroteca can you confirm it?

**Comment by numeroteca** [comment]
It works. Thanks!
